source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

inhibit_all_warnings!
use_frameworks!

target 'Cocktail' do
    pod 'Siesta', '1.1.1'
    pod 'Siesta/UI', '1.1.1'
    pod 'SwiftyJSON', '3.1.4'
    pod 'SDWebImage', '3.8.2'
end